# Generated by Django 5.1.15 on 2026-03-14 01:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("height_cm", models.FloatField(help_text="Altura em centímetros")),
                (
                    "position",
                    models.CharField(
                        choices=[("guard", "Guard"), ("forward", "Forward"), ("center", "Center")],
                        max_length=10,
                    ),
                ),
                ("quality", models.IntegerField(help_text="Qualidade do jogador de 1 a 5")),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
