# Generated by Django 5.1.15 on 2026-03-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="quality",
            field=models.IntegerField(default=0, help_text="Qualidade do jogador de 1 a 5"),
        ),
    ]
