# Generated by Django 5.1.15 on 2026-03-29 02:51

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Organization = apps.get_model("accounts", "Organization")
    for org in Organization.objects.filter(slug=""):
        base_slug = slugify(org.name) or "org"
        slug = base_slug
        counter = 1
        while Organization.objects.filter(slug=slug).exclude(pk=org.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        org.slug = slug
        org.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organization_slug_alter_user_email"),
    ]

    operations = [
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
